name: Release Signed Artifacts

on:
  push:
    branches: [master]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testDebug

  distribute:
    needs: test
    name: Build & Sign Release Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK Build Tools
        run: |
            sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.2
        with: 
          gradlePath: app/build.gradle.kts
          versionCode: ${{ github.run_number }} 
          versionName: 1.0.${{ github.run_number }}

      - name: Build Release Artifacts
        run: ./gradlew bundleRelease assembleRelease

      - name: Sign AAB
        uses: r0adkll/sign-android-release@v1
        id: sign_aab
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.ANDROID_DEVS_ALIAS }}
          keyPassword: ${{ secrets.ANDROID_DEVS_ALIAS_PASSWORD }}

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_apk
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.ANDROID_DEVS_ALIAS }}
          keyPassword: ${{ secrets.ANDROID_DEVS_ALIAS_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "33.0.2"

      - name: Rename APK
        run: |
          cp "${{ steps.sign_apk.outputs.signedReleaseFile }}" "NewNews-v1.0.${{ github.run_number }}.apk"

      - name: Rename AAB
        run: |
          cp "${{ steps.sign_aab.outputs.signedReleaseFile }}" "NewNews-v1.0.${{ github.run_number }}.aab"

      - name: Upload signed AAB as artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-release-aab
          path: NewNews-v1.0.${{ github.run_number }}.aab

      - name: Upload signed APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-release-apk
          path: NewNews-v1.0.${{ github.run_number }}.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: NewNews v1.0.${{ github.run_number }}
          files: |
            NewNews-v1.0.${{ github.run_number }}.apk
            NewNews-v1.0.${{ github.run_number }}.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}